// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GiftModalController from "./gift_modal_controller"
application.register("gift-modal", GiftModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShopPreviewController from "./shop_preview_controller"
application.register("shop-preview", ShopPreviewController)

import SnapshotChartController from "./snapshot_chart_controller"
application.register("snapshot-chart", SnapshotChartController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
